--Actividad 0001
SELECT * FROM PERSONAS p ;
SELECT * FROM GENEROS g ;
SELECT * FROM TIPO_DOCUMENTO td ;
SELECT * FROM ESTUDIANTES e ;
SELECT * FROM PROFESOR p ;
SELECT * FROM PERSONAL ;


SELECT 
	EXTRACT(YEAR FROM SYSDATE),
	p.NOMBRES,
	P.APELLIDO_PATERNO ||' '||
	P.APELLIDO_MATERNO AS APELLIDOS,
	FLOOR(MONTHS_BETWEEN(SYSDATE,P.FECHA_NACIMIENTO)/12) AS FECHA_NACIMIENTO,
	EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM P.FECHA_NACIMIENTO) AS FECHA_NACIMIENTO2, 
	td.sigla AS tipo_documento,
	p.CELULAR
FROM PERSONAS p 
LEFT JOIN TIPO_DOCUMENTO td 
ON p.ID_TIPO_DOCUMENTO = td.ID_TIPO_DOCUMENTO ;
